table 'predictions_duree_vols (1)'

	column Column1
		dataType: string
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	column Column4
		dataType: string
		summarizeBy: none
		sourceColumn: Column4

		annotation SummarizationSetBy = Automatic

	column Column5
		dataType: string
		summarizeBy: none
		sourceColumn: Column5

		annotation SummarizationSetBy = Automatic

	column Column6
		dataType: string
		summarizeBy: none
		sourceColumn: Column6

		annotation SummarizationSetBy = Automatic

	partition 'predictions_duree_vols (1)-bef5e4b3-6597-448d-b16d-ecf062e19b04' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrateur\Downloads\predictions_duree_vols (1).csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

