table 'resultats_analyse_sentimentale (1)'

	column Column1
		dataType: string
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	column Column3
		dataType: string
		summarizeBy: none
		sourceColumn: Column3

		annotation SummarizationSetBy = Automatic

	partition 'resultats_analyse_sentimentale (1)' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Administrateur\Downloads\resultats_analyse_sentimentale (1).csv"),[Delimiter=";", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

