table UserAccess

	column Email
		dataType: string
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column Role
		dataType: string
		summarizeBy: none
		sourceColumn: Role

		annotation SummarizationSetBy = Automatic

	column PageAccess
		dataType: string
		summarizeBy: none
		sourceColumn: PageAccess

		annotation SummarizationSetBy = Automatic

	partition UserAccess = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZY5BCsIwEEWvErIuOYNQ6U4quEy6mMRJOyZEmcymtzcqLai7z/vweNZqhhWLYUyUDlgfTGKk6E5fIGNVR2IMcmcnG9rIGWbUU2d1Bc9UwDDBQl8KJ/1CGNXQ7hIIshpjpIDcvn4YXwZX/sfbGlcmzOZ6Q+9/rSfghEJl3vMa3uEnbHoC", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Email = _t, Role = _t, PageAccess = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Email", type text}, {"Role", type text}, {"PageAccess", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

